/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed-variant": "#004396",
        "tertiary": "#ffbacc",
        "surface-bright": "#38393c",
        "tertiary-container": "#ff8fb2",
        "on-error-container": "#ffdad6",
        "surface-tint": "#ffb86f",
        "secondary-container": "#034eac",
        "on-tertiary-fixed-variant": "#891447",
        "surface-dim": "#121316",
        "primary": "#ffc182",
        "secondary-fixed": "#d8e2ff",
        "background": "#121316",
        "surface": "#121316",
        "inverse-primary": "#8a5100",
        "primary-fixed": "#ffdcbd",
        "on-tertiary-container": "#851044",
        "on-secondary-fixed": "#001a42",
        "inverse-surface": "#e3e2e6",
        "primary-container": "#f0a047",
        "on-surface-variant": "#d8c3b1",
        "on-secondary": "#002e6b",
        "on-tertiary-fixed": "#3f001c",
        "tertiary-fixed-dim": "#ffb1c6",
        "on-error": "#690005",
        "surface-container-lowest": "#0d0e11",
        "on-surface": "#e3e2e6",
        "on-background": "#e3e2e6",
        "surface-variant": "#343538",
        "on-primary-container": "#653a00",
        "outline-variant": "#524437",
        "on-tertiary": "#650031",
        "surface-container": "#1f1f23",
        "inverse-on-surface": "#303034",
        "outline": "#a08d7e",
        "error-container": "#93000a",
        "primary-fixed-dim": "#ffb86f",
        "tertiary-fixed": "#ffd9e1",
        "on-secondary-container": "#aec6ff",
        "on-primary-fixed-variant": "#693c00",
        "secondary": "#aec6ff",
        "error": "#ffb4ab",
        "secondary-fixed-dim": "#aec6ff",
        "surface-container-highest": "#343538",
        "on-primary": "#492900",
        "surface-container-high": "#292a2d",
        "surface-container-low": "#1b1b1f",
        "on-primary-fixed": "#2c1600"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Noto Serif"],
        "display": ["Noto Serif"],
        "body": ["Manrope"],
        "label": ["Manrope"],
        "serif": ["Noto Serif", "serif"],
        "sans": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
